"use client";
import { StyleSheet } from "@react-pdf/renderer";
import { C, CARD_BG, CARD_BORDER } from "./pdf-primitives";

export const S = StyleSheet.create({
  page: { width: "100%", height: "100%", paddingTop: 160, paddingBottom: 110, paddingHorizontal: 32, backgroundColor: C.parchment },
  contentLayer: { flex: 1 },
  section: { marginBottom: 18 },
  headerBox: { flexDirection: "column", alignItems: "center", marginBottom: 10 },
  headerLogo: { width: 100, height: 100, marginBottom: 6 },
  headerText: { alignItems: "center" },
  brandTitle: { fontSize: 15, color: C.deepBrown, letterSpacing: 2, textTransform: "uppercase", fontWeight: 400, textAlign: "center" },
  brandTagline: { fontSize: 8, color: C.agedBrown, letterSpacing: 0.6, marginTop: 3, textAlign: "center" },
  refBadge: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: C.deepLapis, paddingVertical: 5, paddingHorizontal: 10, borderRadius: 3, alignSelf: "flex-start", marginBottom: 12 },
  refText: { fontSize: 8.5, color: C.paleGold, letterSpacing: 1, fontWeight: 400 },
  sectionHeader: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  sectionNum: { backgroundColor: C.deepBrown, borderRadius: 2, paddingVertical: 2, paddingHorizontal: 5, marginRight: 6 },
  sectionNumText: { fontSize: 7, color: C.paleGold, fontWeight: 400 },
  sectionIcon: { marginRight: 6 },
  sectionTitle: { flex: 1, fontSize: 9, color: C.deepBrown, letterSpacing: 1, textTransform: "uppercase", fontWeight: 400 },
  sectionLine: { marginTop: 4, height: 1, backgroundColor: C.royalGold, opacity: 0.5, width: 50 },
  summaryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  summaryCard: { width: "48%", flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: CARD_BG, borderWidth: 1, borderColor: CARD_BORDER, padding: 8 },
  summaryIcon: { width: 20, height: 20, justifyContent: "center", alignItems: "center" },
  summaryLabel: { fontSize: 6, color: C.agedBrown, textTransform: "uppercase", letterSpacing: 0.3, fontWeight: 400 },
  summaryValue: { fontSize: 8, color: C.deepBrown, marginTop: 1 },
  offerBanner: { flexDirection: "row", borderWidth: 1.2, borderColor: C.antiqueGold, borderRadius: 4, overflow: "hidden", backgroundColor: "rgba(232,215,177,0.2)" },
  offerBadge: { backgroundColor: C.rust, paddingVertical: 4, paddingHorizontal: 6, alignItems: "center", justifyContent: "center", minWidth: 40 },
  offerBadgeText: { color: C.paleGold, fontSize: 9, fontWeight: 400 },
  offerBody: { flex: 1, padding: 8 },
  offerTitle: { fontSize: 11, color: C.deepBrown, marginBottom: 2 },
  offerNote: { fontSize: 7.5, color: C.agedBrown, fontStyle: "italic", marginBottom: 4 },
  offerPriceRow: { flexDirection: "row", alignItems: "baseline", gap: 8 },
  offerOld: { fontSize: 8.5, color: C.rust, textDecoration: "line-through" },
  offerNew: { fontSize: 12, color: C.scarab, fontWeight: 400 },
  offerSave: { fontSize: 7, color: C.scarab, marginLeft: "auto" },
  tourTitle: { fontSize: 14, color: C.deepBrown, marginTop: 6, marginBottom: 6 },
  tourDesc: { fontSize: 8.5, color: C.warmBrown, lineHeight: 1.5, marginBottom: 8 },
  dayCard: { backgroundColor: CARD_BG, borderWidth: 1, borderColor: CARD_BORDER, borderRadius: 3, padding: 8, marginBottom: 8 },
  dayHeader: { flexDirection: "row", alignItems: "center", marginBottom: 6, gap: 6 },
  dayBadge: { backgroundColor: C.deepBrown, borderRadius: 2, paddingVertical: 1, paddingHorizontal: 5 },
  dayBadgeText: { fontSize: 7, color: C.paleGold, fontWeight: 400 },
  dayTitle: { fontSize: 10, color: C.deepBrown, flex: 1, fontWeight: 400 },
  dayDesc: { fontSize: 8, color: C.warmBrown, lineHeight: 1.5, marginBottom: 6 },
  panel: { backgroundColor: CARD_BG, borderWidth: 1, borderColor: CARD_BORDER, borderRadius: 3, padding: 8, marginBottom: 6 },
  panelTitle: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 6 },
  panelTitleText: { fontSize: 9, color: C.deepBrown, fontWeight: 400 },
  priceRow: { flexDirection: "row", alignItems: "flex-start", gap: 8, paddingVertical: 4, borderBottomWidth: 0.5, borderBottomColor: CARD_BORDER },
  priceLeft: { flex: 1 },
  priceLeftText: { fontSize: 8.5, color: C.warmBrown, lineHeight: 1.5 },
  priceSub: { fontSize: 7, color: C.agedBrown, marginTop: 1 },
  priceRight: { fontSize: 9, color: C.lapis, fontWeight: 400 },
  notesText: { fontSize: 8.5, color: C.warmBrown, lineHeight: 1.5, marginTop: 6 },
  twoCol: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  col: { width: "48%" },
  colFull: { width: "100%" },
  termsNum: { backgroundColor: C.deepLapis, borderRadius: 2, width: 14, height: 14, justifyContent: "center", alignItems: "center", marginRight: 6 },
  termsNumText: { fontSize: 6, color: C.paleGold, fontWeight: 400 },
  termsText: { fontSize: 7.5, color: C.warmBrown, lineHeight: 1.4 },
  termsLink: { fontSize: 7, color: C.lapis, marginTop: 4, textDecoration: "underline" },
});